### ISSUE TITLE
Loading can lead to an exception being thrown

### ISSUE THREAD

**Issue by Skypr** [NikolaiLMS/PSE-Wahlverfahren-Implementierung#23]
If you load a project that isn't formatted correctly (for example the old file "SequentialTestTrueFalse.beast") an exception gets thrown, but no message is displayed to the user, that tells him that the file doesn't work.

Below I will post the stack dump from my crash:

	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at edu.pse.beast.saverloader.StaticSaverLoaders.SaverLoaderHelper.getNumberAndRemoveNumberPartFromString(SaverLoaderHelper.java:53)
	at edu.pse.beast.saverloader.StaticSaverLoaders.SaverLoaderHelper.parseSaveString(SaverLoaderHelper.java:32)
	at edu.pse.beast.saverloader.ProjectSaverLoader.createFromSaveString(ProjectSaverLoader.java:47)
	at edu.pse.beast.saverloader.FileChooser.loadObject(FileChooser.java:155)
	at edu.pse.beast.parametereditor.UserActions.LoadProjectUserAction.perform(LoadProjectUserAction.java:50)
	at edu.pse.beast.parametereditor.ParameterEditorBuilder$1.actionPerformed(ParameterEditorBuilder.java:208)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For input string: "<projectName>

**Comment by Skypr** [comment]
Maybe instead of immidiately doing "return Integer.valueOf(numberS);" we can surround the cast with a try, catch clause, and set a flag, so a window can tell the user, that his input was wrong formated

**Comment by NikolaiLMS** [comment]
+1

**Comment by NikolaiLMS** [comment]
Fixed in [commit be80a151](https://github.com/NikolaiLMS/PSE-Wahlverfahren-Implementierung/commit/be80a151b8293a1634a95ba4706a365a3f38ca78) by catching all Exceptions thrown by `saverloader.SaverLoader.createFromSaveString` in `saverloader.FileChooser`.
