### ISSUE TITLE
Found a nullpointer exception in the ResultPresenter

### ISSUE THREAD

**Issue by Skypr** [NikolaiLMS/PSE-Wahlverfahren-Implementierung#45]
How to replicate:

In the C-Editor, create an ElectionDescription form the type Single-choice / candidate

then load the FalseProps property and click on analyze

**Comment by Skypr** [comment]
Stack trace:
ANTLR Tool version 4.5.1 used for code generation does not match the current runtime version 4.6ANTLR Tool version 4.5.1 used for code generation does not match the current runtime version 4.6Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at edu.pse.beast.propertylist.View.ResultPresenterWindow.writeElectedMultipleCandidates(ResultPresenterWindow.java:268)
	at edu.pse.beast.propertylist.View.ResultPresenterWindow.presentFailureExample(ResultPresenterWindow.java:246)
	at edu.pse.beast.propertylist.View.ListItem.passMessageToResultWindow(ListItem.java:216)
	at edu.pse.beast.propertylist.View.ListItem.access$1(ListItem.java:201)
	at edu.pse.beast.propertylist.View.ListItem$1.actionPerformed(ListItem.java:81)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Skypr** [comment]
The error occurs because the ResultPresenter thinks that it is an election with seats while it is one with candidates. PLEASE use "ex.getElectionType().getResultTypeSeats()"  to determine, if it is voting with candidates or with seats

**Comment by Skypr** [comment]
Fixed the Bug by replacing some call that determine the election type
